### ISSUE TITLE
I made a Github Actions compatible fork

### ISSUE THREAD

**Issue by JonathanTreffler** [cyberboysumanjay/Carbon-API#16]
If anyone wants to use this project to generate a carbon image inside a Github Action:
I made a fork, that has all the changes necessary to make it work: https://github.com/JonathanTreffler/Carbon-Action

It can be used like this:
```
- uses: JonathanTreffler/Carbon-Action@master
  with:
      code: $(cat code.js)
      language: JavaScript
```

If @cyberboysumanjay is interested in merging this functionality back into his upstream, please contact me :)

This issue doesn't need to be stay open, since it does not require any intervention, just wanted to people know, that they don't have to code this themself, because I already did :)
